<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>_</string>
	</array>
	<key>name</key>
	<string>Arrow</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Single line comment.</string>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.LiveScript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.c</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numeric</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(const|import|let|mut|for|in)\b</string>
					<key>name</key>
					<string>keyword._</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(bool|(u?int(8|16|32|64|128)?)|float(16|32|64|128)?)\b</string>
					<key>name</key>
					<string>storage.type._</string>
				</dict>
			</array>
		</dict>
		<key>numeric</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b[0-9]+\b</string>
					<key>name</key>
					<string>constant.numeric._</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator._</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Assignment operators.</string>
					<key>match</key>
					<string>(=|\+=)</string>
					<key>name</key>
					<string>assignment.operators._</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source._</string>
	<key>uuid</key>
	<string>25066DC2-6B1D-11D9-9D5B-000D93589AF6</string>
</dict>
</plist>
