<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>_</string>
	</array>
	<key>name</key>
	<string>Arrow</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language._</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function._</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([_A-Za-z][_A-Za-z0-9]+)(?=\(.*\)\s*->)</string>
			<key>name</key>
			<string>function._</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function._</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([_A-Za-z][_A-Za-z0-9]+)(?=\s+->)</string>
			<key>name</key>
			<string>function._</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.any-method._</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=(?:do ))([_A-Za-z][_A-Za-z0-9]+)</string>
			<key>name</key>
			<string>function-call._</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.any-method._</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([_A-Za-z][_A-Za-z0-9]+)\(</string>
			<key>name</key>
			<string>function-call._</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin._</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end._</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double._</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin._</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end._</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.single.double._</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numeric</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line_comment</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(const|import|let|mut|for|in|do|foreign|as|if|else)\b</string>
					<key>name</key>
					<string>keyword._</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(bool|(u?int(8|16|32|64|128)?)|float(16|32|64|128)?)\b</string>
					<key>name</key>
					<string>storage.type._</string>
				</dict>
			</array>
		</dict>
		<key>numeric</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b[0-9]+\b</string>
					<key>name</key>
					<string>constant.numeric._</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator._</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(=|\+=|-=|->|\+|-|:|&amp;|^|%|\*|/)</string>
					<key>name</key>
					<string>assignment.operators._</string>
				</dict>
			</array>
		</dict>
		<key>line_comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.number-sign._</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment._</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^((#).*$\n?)</string>
					<key>name</key>
					<string>meta.comment.full-line._</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment._</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(#).*$\n?</string>
					<key>name</key>
					<string>comment.line.number-sign._</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source._</string>
	<key>uuid</key>
	<string>25066DC2-6B1D-11D9-9D5B-000D93589AF6</string>
</dict>
</plist>
