<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple._om/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>_</string>
	</array>
	<key>name</key>
	<string>Arrow</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language._</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function._</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([_A-Za-z][_A-Za-z0-9]+)(?=\(.*\)\s*->)</string>
			<key>name</key>
			<string>function._</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function._</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([_A-Za-z][_A-Za-z0-9]+)(?=\s+->)</string>
			<key>name</key>
			<string>function._</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.any-method._</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=(?:do ))([_A-Za-z][_A-Za-z0-9]+)</string>
			<key>name</key>
			<string>function-call._</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.any-method._</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([_A-Za-z][_A-Za-z0-9]+)\(</string>
			<key>name</key>
			<string>function-call._</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin._</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end._</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double._</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_escaped_char</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin._</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end._</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.single.double._</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_escaped_char</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#numeric</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#line_comment</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?x)
						\b(
						const|
						import|
						let|
						mut|
						for|
						in|
						do|
						foreign|
						as|
						and|
						or|
						not|
						if|
						else|
						use|
						public|
						private|
						class|
						unsafe
						)\b
					</string>
					<key>name</key>
					<string>keyword._</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?x)
						\b(
						bool|
						(u?int(8|16|32|64|128)?)|
						float(16|32|64|128)?|
						)\b
					</string>
					<key>name</key>
					<string>storage.type._</string>
				</dict>
			</array>
		</dict>
		<key>numeric</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?x)
						\b
						(0[bB][0-1]+)|
						(0[oO][0-7]+)|
						(0[xX][A-Fa-f0-9]+)|
						([0-9]+\.[0-9]+([Ee][-+]?[0-9]+)?)|
						([0-9]+([Ee][-+]?[0-9]+)?)|
						([0-9]+)
						\b
					</string>
					<key>name</key>
					<string>constant.numeric._</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator._</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)
						(
						=|
						\+=|
						-=|
						->|
						\+|
						-|
						:|
						&amp;|
						^|
						%|
						\*|
						==|
						&gt;=|
						&lt;=|
						&gt;|
						&lt;|
						/)
					</string>
					<key>name</key>
					<string>assignment.operators._</string>
				</dict>
			</array>
		</dict>
		<key>line_comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.line.number-sign._</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment._</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^((#).*$\n?)</string>
					<key>name</key>
					<string>meta._omment.full-line._</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment._</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(#).*$\n?</string>
					<key>name</key>
					<string>comment.line.number-sign._</string>
				</dict>
			</array>
		</dict>
		<key>string_escaped_char</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\\['"\\abfnrtv])|(\\[xX][a-fA-F0-9]{2})|(\\u[a-fA-F0-9]{4})|(\\U[a-fA-F0-9]{8})</string>
					<key>name</key>
					<string>constant._haracter.escape._</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>invalid.illegal.unknown-escape._</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source._</string>
	<key>uuid</key>
	<string>25066DC2-6B1D-11D9-9D5B-000D93589AF6</string>
</dict>
</plist>
